# Generated by Django 4.2.1 on 2023-05-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departurecity',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flightnumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.flight'),
        ),
    ]
